### ISSUE TITLE
string index out of range 

### ISSUE THREAD

**Issue by carponoid** [ram2141/einthusan#2]
Able to navigate till the movie section, once you click on a title below exception is thrown 

2020-03-21 21:01:56.557 T:1920   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: string index out of range
                                            Traceback (most recent call last):
                                              File "C:\Users\Praveen\AppData\Roaming\Kodi\addons\plugin.video.einthusan\default.py", line 611, in <module>
                                                function_map[mode](name, url, language, mode)
                                              File "C:\Users\Praveen\AppData\Roaming\Kodi\addons\plugin.video.einthusan\default.py", line 368, in play_video
                                                get_movie(s,mainurl,mainurlajax, headers)
                                              File "C:\Users\Praveen\AppData\Roaming\Kodi\addons\plugin.video.einthusan\default.py", line 382, in get_movie
                                                r=decodeEInth(lnk)
                                              File "C:\Users\Praveen\AppData\Roaming\Kodi\addons\plugin.video.einthusan\default.py", line 328, in decodeEInth
                                                r=lnk[0:t]+lnk[-1]+lnk[t+2:-1]
                                            IndexError: string index out of range
                                            -->End of Python script error report<--
2020-03-21 21:01:56.557 T:1920   DEBUG: CPythonInvoker::onExecutionDone(5, C:\Users\Praveen\AppData\Roaming\Kodi\addons\plugin.video.einthusan\default.py)

**Comment by ram2141** [comment]
Hello @carponoid ,
Try to update your Kodi to the latest version and also uninstall old einthusan repo. Then install this latest repo from the below link. I just checked it and mine works fine. 

[Download Einthusan Repo](https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan.zip?raw=true)

**Comment by avanand-git** [comment]
Fresh install 18.6, and Einthusan Add give exact same exception on Mac.

**Comment by nraddy** [comment]
https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan/default.py#L382

That's where this error is coming from. As that variable is unused, it can be safely removed. Did a local edit which fixed the issue for me.
Reason for it breaking is to do with changes in html response in the response to get website call.

I also moved the "einthusan.tv" base url to "addon" settings. This would allow one to edit the URL whenever the website moves to some other domain, removing the need to keep updating the plugin.
I wonder what's the best way to contribute to this code base.

Screenshot:
<img width="479" alt="Einthusan add-on settings" src="https://user-images.githubusercontent.com/25803390/77279988-2bda3580-6c91-11ea-9338-20ddc8a6cdc2.png">

**Comment by ram2141** [comment]
Thanks @nraddy for your help. I have temporarily fixed and removed line 382. It should fix the issue. 

@avanand-git  download updated repo. 

[Download updated repo](https://github.com/ram2141/einthusan/blob/master/plugin.video.einthusan.zip?raw=true)

**Comment by carponoid** [comment]
@nraddy  @ram2141  Thanks! Works for me now, closing the issue.
