### ISSUE TITLE
einthusan Kodi not working

### ISSUE THREAD

**Issue by rnanjun** [ram2141/einthusan#8]
This is the error I am getting when clicking on a movie on Einthusan. Any help would be appreciated

2020-05-02 03:43:53.788 T:2601513840   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.IndexError'>
                                            Error Contents: list index out of range
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 653, in <module>
                                                function_map[mode](name, url, language, mode)
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 401, in play_video
                                                get_movie(s,mainurl,mainurlajax, headers)
                                              File "/storage/.kodi/addons/plugin.video.einthusan/default.py", line 413, in get_movie
                                                lnk=re.findall('data-ejpingables=["\'](.*?)["\']',htm)[0]
                                            IndexError: list index out of range
                                            -->End of Python script error report<--

**Comment by eintamil** [comment]
Hello, try EinTamil Repo: https://eintamil.github.io/
Please use Einthusan2 for Kodi 18.x (Python 2.x)
Please use Einthusan3 for Kodi 19.x (Python 3.x)
If any issues, raise at https://github.com/eintamil/repository.eintamil/issues

**Comment by rnanjun** [comment]
Thanks a ton. It works now

**Comment by psychokoelie** [comment]
Thanks need new movies
